name: antinvestor_api_ledger
description: Dart client library for Ant Investor Ledger Service - Financial ledger and accounting
version: 1.50.6
repository: https://github.com/antinvestor/apis
homepage: https://github.com/antinvestor/apis/tree/main/dart/ledger
issue_tracker: https://github.com/antinvestor/apis/issues

environment:
  sdk: ^3.3.0

dependencies:
  protobuf: ^4.2.0
  connectrpc: ^1.0.0
  fixnum: ^1.1.0
  antinvestor_api_common: ^1.50.3

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.0

topics:
  - grpc
  - protobuf
  - api-client
  - ledger
