name: antinvestor_api_files
description: Dart client library for Ant Investor Files Service - File upload, download, and media management
version: 1.50.8
repository: https://github.com/antinvestor/apis
homepage: https://github.com/antinvestor/apis/tree/main/dart/files
issue_tracker: https://github.com/antinvestor/apis/issues

environment:
  sdk: ^3.3.0

dependencies:
  protobuf: ^4.2.0
  connectrpc: ^1.0.0
  fixnum: ^1.1.0
  antinvestor_api_common: ^1.50.4

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.0

topics:
  - grpc
  - protobuf
  - api-client
  - files
  - media
