name: antinvestor_api_profile
description: Dart client library for Ant Investor Profile Service - User profiles and account management
version: 1.51.6
repository: https://github.com/antinvestor/apis
homepage: https://github.com/antinvestor/apis/tree/main/dart/profile
issue_tracker: https://github.com/antinvestor/apis/issues

environment:
  sdk: ^3.3.0

dependencies:
  protobuf: ^4.2.0
  connectrpc: ^1.0.0
  fixnum: ^1.1.0
  antinvestor_api_common: ^1.51.4

dev_dependencies:
  lints: ^6.0.0
  test: ^1.28.0

topics:
  - grpc
  - protobuf
  - api-client
  - profile
