name: Test Api

on: [ push ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout new code for testing
        uses: actions/checkout@v6
      - name: Setup go testing infrastructure
        uses: actions/setup-go@v6
        with:
          go-version: 'stable'

      - name: Run build setup
        env:
          GOTOOLCHAIN: go1.25.0+auto
          BUF_TOKEN: ${{ secrets.BUF_TOKEN }}
        run: make
